#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/wait.h>
#include <string.h>
#include <time.h>

#define NUM_CHILDS 5

int generateNum()
{
	struct timespec ts;
	clock_gettime(CLOCK_MONOTONIC, &ts);
	srand((unsigned int)(ts.tv_nsec ^ ts.tv_sec ^ getpid() ^ rand()));
	return (rand() % 500) + 1;
}

int main()
{
	srand(time(NULL) ^ getpid());
	pid_t pids[NUM_CHILDS];
	int pipes[NUM_CHILDS + 1][2];

	for (int i = 0; i < NUM_CHILDS + 1; i++)
	{
		if (pipe(pipes[i]) == -1)
		{
			perror("pipe");
			exit(EXIT_FAILURE);
		}
	}

	for (int i = 0; i < NUM_CHILDS; i++)
	{
		pids[i] = fork();

		if (pids[i] == -1)
		{
			perror("fork");
			exit(EXIT_FAILURE);
		}

		if (pids[i] == 0)
		{
			int received;
			int sent;
			int generated = generateNum();
			printf("%d generated num: %d\n", getpid(), generated);

			close(pipes[i][1]);		// fechar a escrita de onde recebe
			close(pipes[i + 1][0]); // frchar leitura para onde envia

			read(pipes[i][0], &received, sizeof(int));

			printf("%d received in pipe %d: %d\n", getpid(), i, received);

			if (received > generated)
			{
				sent = received;
			}
			else if (generated > received)
			{
				sent = generated;
			}
			else
			{
				sent = generated;
			}

			printf("%d sent in pipe %d: %d\n", getpid(), i + 1, sent);

			write(pipes[i + 1][1], &sent, sizeof(int));

			exit(EXIT_SUCCESS);
		}
	}

	// apenas pai
	for (int i = 1; i < NUM_CHILDS; i++)
	{
		close(pipes[i][0]);
		close(pipes[i][1]);
	}
	
	int generatedByParent = generateNum();
	printf("Generated by parent: %d\n", generatedByParent);

	close(pipes[0][0]);
	close(pipes[NUM_CHILDS][1]);

	write(pipes[0][1], &generatedByParent, sizeof(int));

	int greatest;
	read(pipes[NUM_CHILDS][0], &greatest, sizeof(int));
	printf("Final greatest: %d\n", greatest);

	close(pipes[0][1]);
	close(pipes[NUM_CHILDS][0]);

	// wait for all children to finish
	for (int i = 0; i < NUM_CHILDS; i++) {
		wait(NULL);
	}

	return 0;
}
